"""Context-file resolution for the investigator.

The investigator needs a small map of on-disk paths it can grep — typically the cube
package, the agent package, and the cube-harness source. That map lives in
`<experiment_dir>/investigation_context.md` as a fenced ```paths block:

    ```paths
    cube_package: /abs/path/to/cubes/foo
    agent_package: /abs/path/to/cube_harness/agents
    ```

The file is generated by the benchmark-context sub-agent (`benchmark_context_agent.generate_context_file`)
and validated here. There is no longer a venv-walk fallback — the sub-agent
is the canonical producer; missing or unparseable files raise so the failure
is loud rather than silently wrong.

`_load_experiment_view` is also kept here because the investigator prompt builder
references the agent / benchmark `_type` strings from `experiment_config.json`
even when the sub-agent has already produced the context file.
"""

from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from cube_harness.experiment import Experiment

logger = logging.getLogger(__name__)

# Matches a fenced block opening with ```paths (case-insensitive); captures the
# block body up to the closing fence. The block contains one path per line; lines
# may be `name: /abs/path` or just `/abs/path`. Blank lines and `# comments`
# are ignored.
_PATHS_FENCE_RE = re.compile(r"```\s*paths\s*\n(.*?)```", re.DOTALL | re.IGNORECASE)
INVESTIGATION_CONTEXT_FILENAME = "investigation_context.md"


@dataclass
class _ExperimentView:
    """A view of `experiment_config.json` that prefers the typed `Experiment` object
    but falls back to a raw dict when `_type` references can't be imported (e.g.
    the experiment was run with an agent class that no longer exists locally)."""

    experiment: Experiment | None
    raw: dict[str, Any]

    @property
    def agent_dotted(self) -> str:
        if self.experiment is not None:
            t = type(self.experiment.agent_config)
            return f"{t.__module__}.{t.__name__}"
        return self.raw.get("agent_config", {}).get("_type", "unknown")

    @property
    def benchmark_dotted(self) -> str:
        if self.experiment is not None:
            t = type(self.experiment.benchmark_config)
            return f"{t.__module__}.{t.__name__}"
        return self.raw.get("benchmark_config", {}).get("_type", "unknown")

    @property
    def infra_dotted(self) -> str | None:
        if self.experiment is not None and self.experiment.infra is not None:
            t = type(self.experiment.infra)
            return f"{t.__module__}.{t.__name__}"
        return self.raw.get("infra", {}).get("_type") if isinstance(self.raw.get("infra"), dict) else None


def _load_experiment_view(path: Path) -> _ExperimentView:
    """Load experiment_config.json. Try typed Experiment first; fall back to dict.

    Typed load can fail in many ways: a referenced class was renamed
    (`ImportError`), removed (`AttributeError`, when `_type` is `__main__.X` from
    an ad-hoc script), or changed shape (`ValidationError`). Any failure falls
    back to the dict view, which is always good enough for the investigator — it only
    needs the `_type` strings and a few well-known fields.
    """
    if not path.exists():
        return _ExperimentView(experiment=None, raw={})
    raw = json.loads(path.read_text())
    try:
        return _ExperimentView(experiment=Experiment.load_config(str(path)), raw=raw)
    except Exception as e:
        logger.info(
            "experiment_config.json could not be loaded as Experiment (%s: %s) — falling back to dict view.",
            type(e).__name__,
            e,
        )
        return _ExperimentView(experiment=None, raw=raw)


def find_default_context_file(experiment_dir: Path) -> Path:
    """Return `<experiment_dir>/investigation_context.md` if it exists, else raise.

    Used by `_investigate_episode_impl` to decide whether to invoke the benchmark-context
    sub-agent. Raising — rather than returning `None` — is intentional: callers
    catch `FileNotFoundError` and call the sub-agent; if the sub-agent runs but
    still fails to produce a file, the error propagates with a useful path.
    """
    path = Path(experiment_dir) / INVESTIGATION_CONTEXT_FILENAME
    if not path.exists():
        raise FileNotFoundError(path)
    return path


def _parse_paths_block(text: str) -> list[tuple[str | None, Path]]:
    """Extract (name, path) pairs from the first ```paths block in `text`.

    Each non-empty, non-comment line is `name: /abs/path` or `/abs/path` (no name).
    Returns an empty list if no fence is found — caller decides what to do.
    """
    match = _PATHS_FENCE_RE.search(text)
    if match is None:
        return []
    pairs: list[tuple[str | None, Path]] = []
    for raw_line in match.group(1).splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if ":" in line and not line.startswith("/"):
            name, _, path_str = line.partition(":")
            pairs.append((name.strip() or None, Path(path_str.strip()).expanduser()))
        else:
            pairs.append((None, Path(line).expanduser()))
    return pairs


def validate_context_file(path: Path) -> dict[str, Path]:
    """Parse a `investigation_context.md` and verify every listed path exists locally.

    Returns a `name → path` map (auto-naming entries that lack a label). Raises
    `FileNotFoundError` on the first missing path with a message identifying the
    offending entry — this catches the common failure mode where the
    benchmark-context sub-agent hallucinates a path.

    Raises `ValueError` if the file lacks a ```paths fenced block at all.
    """
    path = Path(path)
    text = path.read_text()
    pairs = _parse_paths_block(text)
    if not pairs:
        raise ValueError(f"{path} has no ```paths fenced block")

    resolved: dict[str, Path] = {}
    for idx, (name, p) in enumerate(pairs):
        if not p.exists():
            raise FileNotFoundError(f"{path}: listed path does not exist: {p} (entry {idx}, name={name!r})")
        key = name or f"path_{idx}"
        resolved[key] = p
    return resolved
