name: Ruff
on: [pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Ruff linting
        uses: astral-sh/ruff-action@v3
        with:
          args: check --diff
          src: "./src"
      - name: Run Ruff format check
        uses: astral-sh/ruff-action@v3
        with:
          args: format --diff
          src: "./src"
